server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pingpong
    password:
    driver-class-name: org.h2.Driver #h2 데이터베이스 이용
    username: sa

  jpa:
    hibernate:
      ddl-auto: create #자동으로 테이블 만들어줌
    properties:
      hibernate:
        # show_sql: true 이건 system out을 통해 출력하기 때문에 이건 쓰면 안됨 그대신 밑에서 로그 씀
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug #hibernate가 생성하는 sql이 다 보임
    org.hibernate.type: trace # 쿼리 파라미터 로깅